@startuml
autonumber

== PhoneWindow 创建过程==
--> ActivityThread:handleLaunchActivity
ActivityThread -> ActivityThread:performLaunchActivity
ActivityThread --> Activity:attach
Activity -> PhoneWindow:new
PhoneWindow -> Window:super
PhoneWindow -> LayoutInflater:from(context)

Activity -> Window:setCallback
Activity -> Window:setSoftInputMode

Activity -> Window:setWindowManager

Window -> WindowManagerImpl:createLocalWindowManager

==setContentView==
ActivityThread -> Activity:onCreate
Activity --> Activity:setContentView
Activity -> PhoneWindow:setContentView

note left
这一步也可能通过另一流程创建
AppCompatDelegateImpl.setContentView
ensureSubDecor
createSubDecor
PhoneWindow.getDecorView()
end note


PhoneWindow -> PhoneWindow:installDecor
PhoneWindow -> PhoneWindow:mDecor = generateDecor(-1);
PhoneWindow -> DecorView:new

PhoneWindow -> PhoneWindow:mContentParent = generateLayout(mDecor);

PhoneWindow -> DecorView:layoutResource = R.layout.screen_simple;\n mDecor.onResourcesLoaded(mLayoutInflater, layoutResource);
DecorView -> DecorView : addView()

PhoneWindow -> DecorView: ViewGroup contentParent = (ViewGroup)findViewById(ID_ANDROID_CONTENT);
DecorView --> PhoneWindow


== View 加载过程==
PhoneWindow -> LayoutInflater:inflate
note right
rInflateChildren
inflate
createViewFromTag
createView
constructor.newInstance(args);
end note

LayoutInflater -> ViewGroup:addView

--> ActivityThread:handleResumeActivity
ActivityThread -> WindowManagerImpl:addView

WindowManagerImpl -> ViewRootImpl:new
WindowManagerImpl -> ViewRootImpl:setView
ViewRootImpl -> ViewRootImpl:requestLayout，首次请求

ViewRootImpl ->mWindowSession: addToDisplay
@enduml